import Head from "next/head";
// import Image from "next/image";
// import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import sanityClients from "../sanity";
// import createClient from '../sanity'
// import { Posts } from "../typings";
// import Link from "next/link";
import imageUrlBuilder from "@sanity/image-url";
import dynamic from "next/dynamic";


const Hero = dynamic(() => import("../components/Hero"), { ssr: false });
const Trending = dynamic(() => import("../components/Trending"), {
  ssr: false,
});

export default function Home({ posts }) {
  const builder = imageUrlBuilder(sanityClients);

  function urlFor(source) {
    return builder.image(source);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Peculiar Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero post={posts} urlFor={urlFor} />

        <Trending post={posts} urlFor={urlFor} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    title,
    _createdAt,
    description,
    author -> {
    name,
    image,
  },
  
  mainImage,
  slug
  
    }`;

  const posts = await sanityClients.fetch(query);
  const product = await sanityClients.fetch(query);

  return {
    props: {
      posts,
      product,
    },
  };
};
