import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import sanityClients from "../sanity";
// import createClient from '../sanity'
import { Post } from "../typings";
import Hero from "../components/Hero";
import Link from "next/link";
import imageUrlBuilder from "@sanity/image-url";

interface Props {
  posts: [Post];
}

export default function Home({ posts }: Props) {
  const builder = imageUrlBuilder(sanityClients);

  function urlFor(source) {
    return builder.image(source);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Navbar />
        <Hero />

        <div className=" grid grid-cols-1 md:grid-cols-4  justify-center align-middle gap-6 py-11">
          {posts?.map((post) => (
            <div key={post._id} className=" bg-slate-200   ">
          
              <img src={urlFor(post.mainImage).width(400).height(300).url()!}  className="w-full"/>
              <div className='p-5'>
                <Link href={`/post/${post.slug.current}`}>
                  <h1 className=' text-lg text-cyan-600 text-center cursor-pointer'>{post.title}</h1>
                </Link>

                <div className='flex justify-between align-center py-3'>
                <p>By {post.author.name}</p>
              <img src={urlFor(post.author.image).url()!}  className=' h-10 rounded-full object-cover' />

                </div>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    title,
    
    author -> {
    name,
    image,
  },
  
  mainImage,
  slug
  
    }`;

  const posts = await sanityClients.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
